Description: >
  This template deploys routes to api gateway rest
Parameters:
  NetworkLoadBalancerDNS:
    Description: A network load balancer DNS
    Type: String

  Port:
    Type: Number
    Description: Port of mslogon

  APIGatewayNLBId:
    Type: String
    Description: Api Gateway

  APIGatewayNLBRootId:
    Type: String
    Description: Api Gateway

  PrivateAPIGWvpcLinkId:
    Type: String

Resources:
  #LOGON
  MSLogonResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayNLBId
      ParentId: !Ref APIGatewayNLBRootId
      PathPart: ms-logon

  MSLogonResourceProxy:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayNLBId
      ParentId: !Ref MSLogonResource
      PathPart: "{proxy+}"

  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: ProxyAll
      RestApiId: !Ref APIGatewayNLBId
      ResourceId: !Ref MSLogonResourceProxy
      HttpMethod: ANY
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        ConnectionId: !Ref PrivateAPIGWvpcLinkId
        ConnectionType: VPC_LINK
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
        Uri: !Sub http://${NetworkLoadBalancerDNS}:${Port}/ms-logon/{proxy}
