AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template deploys a Rest Api Gateway to Private Network Load Balancer
Parameters:
  NetworkLoadBalancerARN:
    Description: A network load balancer ARN
    Type: String

  StageName:
    Description: A Stage
    Type: String
    Default: dev

Resources:
  RestApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: RestVPCLink
      Description: Rest Vpc Link
      TargetArns:
        - !Ref NetworkLoadBalancerARN

  RestApiGateway:
    DependsOn: RestApiGatewayVpcLink
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApiGateway
      Description: Rest Api Gateway Description
      Parameters:
        endpointConfigurationTypes: REGIONAL

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - "DummyMethod"
    Properties:
      RestApiId: !Ref RestApiGateway
      Description: Rest api gateway deployment

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref StageName
      Description: !Sub ${StageName} Stage
      RestApiId: !Ref RestApiGateway
      DeploymentId: !Ref Deployment
      Variables:
        Stack: !Ref StageName

  DummyMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      OperationName: Dummy
      RestApiId: !Ref RestApiGateway
      ResourceId: !GetAtt
        - RestApiGateway
        - RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK

Outputs:
  APIURL:
    Description: Invoke URL
    Value: !Sub https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/

  RestApiGateway:
    Description: Rest Api Gateway Id
    Value: !Ref RestApiGateway
    Export:
      Name: RestApiGatewayId

  RestApiGatewayRootId:
    Description: Rest Api Gateway Root Id
    Value: !GetAtt
      - RestApiGateway
      - RootResourceId
    Export:
      Name: RestApiGatewayRootId

  RestApiGatewayVpcLink:
    Description: Private API GW vpcLink Id
    Value: !Ref RestApiGatewayVpcLink
    Export:
      Name: RestApiGatewayVpcLinkId

  Deployment:
    Description: Rest Api Gateway Deployment Id
    Value: !Ref Deployment
    Export:
      Name: RestApiGatewayDeploymentId
