AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a SNS Fifo that delivers messages to SQS Fifo

Parameters:
  TopicName:
    Type: String
    Default: topic-user-bevcapital
    Description: Topic Name that will receive the messages

  QueueName:
    Type: String
    Default: queue-user-bevcapital
    Description: Queue name that will devliver the messages

Resources:
  AppSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${TopicName}.fifo
      FifoTopic: true
      DisplayName: !Ref TopicName
      Subscription:
        - Endpoint: !GetAtt AppQueue.Arn
          Protocol: sqs

  AppSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sns:Subscribe
              - sns:Receive
            Resource:
              - !Ref AppSNSTopic
      Topics:
        - !Ref AppSNSTopic

  AppQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${QueueName}.fifo
      DelaySeconds: 5
      FifoQueue: true
      MaximumMessageSize: 262144 #256 KiB
      MessageRetentionPeriod: 120
      ReceiveMessageWaitTimeSeconds: 10

  AppQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - Ref: AppQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueUrl
              - sqs:GetQueueAttributes
              - sqs:ListQueueTags
              - sqs:ChangeMessageVisibility
            Resource:
              - !GetAtt AppQueue.Arn

Outputs:
  AppQueue:
    Description: URL of Amazon SQS Queue
    Value:
      Ref: AppQueue
    Export:
      Name: AppQueueURL

  AppQueueARN:
    Description: ARN of AmazonSQS Queue
    Value:
      Fn::GetAtt:
        - AppQueue
        - Arn

  AppSNSTopicARN:
    Description: ARN of SNS Topic
    Value:
      Ref: AppSNSTopic
    Export:
      Name: AppSNSTopicARN

  AppSNSTopicName:
    Description: Name of SNS Topic
    Value:
      Fn::GetAtt:
        - AppSNSTopic
        - TopicName
