Description: >
  This template deploys an Network Load Balancer
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: development

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

  PublicSubnet1:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: AWS::EC2::Subnet::Id

  NLBScheme:
    Type: String
    Description: Choose network load balancer scheme
    Default: internal
    AllowedValues: ["internet-facing", "internal"]

  LoadBalancerCertificateArn:
    Description: "Optional Amazon Resource Name (ARN) of the certificate to associate with the load balancer."
    Type: String
    Default: ""

Conditions:
  HasLoadBalancerCertificateArn:
    !Not [!Equals [!Ref LoadBalancerCertificateArn, ""]]

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-nlb
      Type: network
      Scheme: !Ref NLBScheme
      SubnetMappings:
        - AllocationId: !GetAtt
            - FirstEIP
            - AllocationId
          SubnetId: !Ref PublicSubnet1
        - AllocationId: !GetAtt
            - SecondEIP
            - AllocationId
          SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  FirstEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  SecondEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  # We define a default target group here, as this is a mandatory Parameters
  # when creating an Application Load Balancer Listener. This is not used, instead
  # a target group is created per-service in each service template (../services/*)
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default-nlb
      VpcId: !Ref VPC
      Port: 80
      Protocol: TCP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60


Outputs:
  LoadBalancer:
    Description: A reference to the Network Load Balancer
    Value: !Ref LoadBalancer
    Export:
      Name: ARNLoadBalancerBevCapital

  LoadBalancerUrl:
    Description: The URL of the Network Load Balancer
    Value: !GetAtt LoadBalancer.DNSName

