AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template deploys a Http Api Gateway to Private Application Load Balancer
Parameters:
  Subnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id

  HttpListener:
    Type: String
    Description: A Listener of the Application Load balancer

  AcmCertArn:
    Type: String
    Description: ARN of the Amazon Certificate Manager cert to use for SSL

  BackendDomainName:
    Type: String
    Default: "bev-ticketing-ecomapp.xyz"
    Description: Backend domain name

Conditions:
  HasBackendDomainName: !Not [!Equals [!Ref "BackendDomainName", ""]]

Resources:
  HttpApiGatewayVpcLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: HttpVPCLink
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetIds: !Ref Subnets

  HttpApiGateway:
    DependsOn: HttpApiGatewayVpcLink
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: APIGateway-Http
      ProtocolType: HTTP

  HttpApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      AutoDeploy: true
      ApiId: !Ref HttpApiGateway

  HttpApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: Private Integration
      ApiId: !Ref HttpApiGateway
      ConnectionId: !Ref HttpApiGatewayVpcLink
      ConnectionType: VPC_LINK
      IntegrationMethod: ANY
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Ref HttpListener
      PayloadFormatVersion: "1.0"

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApiGateway
      RouteKey: "GET /"
      Target: !Join
        - /
        - - integrations
          - !Ref HttpApiGatewayIntegration

  BackDomainName:
    Condition: HasBackendDomainName
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref BackendDomainName
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref AcmCertArn

  BackDomainNameMapping:
    Condition: HasBackendDomainName
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApiGateway
      DomainName: !Ref BackendDomainName
      Stage: !Ref HttpApiGatewayStage

Outputs:
  APIURL:
    Description: Invoke URL
    Value: !Sub https://${HttpApiGateway}.execute-api.${AWS::Region}.amazonaws.com/

  HttpApiGateway:
    Description: Http Api Gateway Id
    Value: !Ref HttpApiGateway
    Export:
      Name: HttpApiGatewayId

  HttpApiGatewayIntegration:
    Description: Http Api Gateway Integration Id
    Value: !Ref HttpApiGatewayIntegration
    Export:
      Name: HttpApiGatewayIntegrationId
