AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a RedisSecret for user and password

Parameters:
  SecretName:
    Description: Name of the secret
    Type: String
    Default: CacheSecretBevCapital

  CacheEndpoint:
    Description: The cache db endpoint + port (cacheendpoint.com:6379)
    Type: String

  CachePassword:
    NoEcho: true
    Description: The database password of the cache db
    Type: String

Resources:
  CacheSecretKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  CacheSecretKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: alias/CacheSecretKey
      TargetKeyId: !Ref CacheSecretKey

  CacheSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      KmsKeyId: !Ref CacheSecretKey
      SecretString: !Join
        - ""
        - - "{ "
          - '"cacheEndpoint": "'
          - !Ref CacheEndpoint
          - '",'
          - '"cachePassword": "'
          - !Ref CachePassword
          - '" }'
